### PR TITLE
Color picker

### PR DESCRIPTION
**Pull request by bjarnef**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

- [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
- [ ] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.UI/blob/dev/docs/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by iOvergaard** [comment]
Hi @bjarnef 

We would still like to include this in the library. May I ask what your general feeling of these components are? Can we help you in any way?

As a note, I see that we updated the way that packages are structured especially regarding the index.ts and package.json files, so you might want to try and copy from other packages or recreate the package structure using `npm run new-package`.

Thanks for all your work thus far :)

**Comment by bjarnef** [comment]
Hi @iOvergaard 

So far I think the components in the UI library is looking great, but I also think some of the components mentioned here works great - and maybe we can get some inspiration from these.
https://github.com/umbraco/Umbraco.UI/issues/91#issuecomment-1015797903

Regarding a Color Picker component I think it need to be several components.

- `uui-color-picker` (consisting of several sub components I guess - the ones listed below)
- `uui-color-picker-slider` (I think the same component could be used as hue slider and alpha/opacity slider).
- `uui-color-spectrum` or `uui-color-palette` for the color spectrum area.
- `uui-color-swatches` (it could be useful if this could be used in e.g. property editors or at the current icon color picker, but it may change it the new backoffice UI).

Furthermore it may use some of the existing components for input and buttons in the color picker.

Yeah, I noticed the structure changed a bit, so I need to have a look at the new structure.

**Comment by iOvergaard** [comment]
Make sure to commit the latest package-lock.json file (after upgrading of node/npm and delete the old file first) 👍

**Comment by bjarnef** [comment]
Still much work to do, but this is a start 😁 

https://user-images.githubusercontent.com/2919859/167907223-2c9d6aff-4936-4c4a-8660-84c406e1d933.mp4

**Comment by bjarnef** [comment]
@iOvergaard a cool feature is the EyeDropper API supported by some modern browsers: https://caniuse.com/?search=EyeDropper

image

This allow to pick any color on screen also outside browser window.

https://user-images.githubusercontent.com/2919859/169276764-69608f9f-491d-4235-a787-37ba9868e615.mp4

I am probably missing something to show the "colorpicker" icon here: https://github.com/umbraco/Umbraco.UI/blob/a0ddba4982bf614c1d17d17aec6519031c0efc81/packages/uui-color-picker/lib/uui-color-picker.element.ts#L441

At the moment the slider is the same component, but I think we may need to split this into a `hue-slider` and `opacity-slider` to apply the correct styling, so opacity slider has a transparent background with a color overlay which adjust it transparency as the slider value change.

**Comment by bjarnef** [comment]
Not sure it this is the right approach, but in work if I wrap the icon:

```
<uui-icon-registry-essential>
    <uui-icon name="colorpicker"></uui-icon>
</uui-icon-registry-essential>
```

image

**Comment by bjarnef** [comment]
@iOvergaard @nielslyngsoe did you have a chance to look at these changes?
Regarding the swatches do we need to separate each swatch button - it could eventually use `uui-button` but it we want to keep to current behaviour in backoffice when labels are used, we may use a adjusted layout based on attributes/properties and create a `uui-swatch` component.. or maybe we could switch between `uui-button` and `uui-card` components.

Regarding the alpha/opacity and hue slider I am not sure it can be done in same component, depending on how the styling changes as you adjust the slider value.

**Comment by iOvergaard** [comment]
Hi @bjarnef 

No, sorry. Have not had a chance yet. I like the work you have done so far.

In your mind, what needs to be done before this is complete?

Will have a deep dive into it sometime after Codegarden - hope that's all right :)

**Comment by bjarnef** [comment]
Hi @iOvergaard 

There's a few things, which need to be done.
- Selection in the swatch/swatches
- Separate hue and opacity/alpha slider if we can't make it work using same conponent.
- Update preview color
- Correct transform/convert of colors. Currently using a fork of TinyColor, but I considering whether Colord library may be a better choice.

**Comment by iOvergaard** [comment]
Hi @bjarnef 

This is currently targeting an old branch and I'm doing some cleanup, so will just close this one. We will have to retarget `v1/dev` at some point :-)

**Comment by bjarnef** [comment]
@iOvergaard okay, we can't just re-target the new branch? 🙂

**Comment by iOvergaard** [comment]
Sorry @bjarnef , I couldn't retarget it and had to delete the target branch, so it autoclosed the PR. You should be able to create a new PR. Sorry for the inconvenience.

**Comment by bjarnef** [comment]
@iOvergaard meanwhile, could you and @nielslyngsoe add some feedback on this request: https://github.com/umbraco/Umbraco.UI/pull/112#issuecomment-1152370074

**Selection in the swatch/swatches**
Should each swatch be a separate component and use the selectable mixin?

**Separate hue and opacity/alpha slider**
Currently same component, but it may need to be two separate components, e.g. to change color in opacity slider.

**Correct transform/convert of colors**
Do you have some preferences regarding this? Currently it is using a fork of TinyColor, but the Shoelace library is using Color library, but the Colord library looks great as it is lightweight, extendable, immutable and splitted into smaller modules: https://github.com/omgovich/colord#benchmarks

**Comment by iOvergaard** [comment]
Yes sure, @bjarnef! We'll get to it when people are back from holiday :-)

**Comment by nielslyngsoe** [comment]
@bjarnef  regarding "<uui-icon-registry-essential> seems like an extra layer, which I think developers can easily forget." Its only something you will need in the storybook stories for now. In New Backoffice it will be provided. We could consider embedding it in storybook as well so its never needed to add, but for now I like to make it explicit, as some might use this UI in other contexts, other projects.

**Comment by nielslyngsoe** [comment]
@bjarnef here is some thoughts of mine regarding these topics:

**Selection in the swatch/swatches**
Yes, I think it would be best if each little box was a web component on its own, using the selectable mixin sounds good, in this way you can also use the swatches without them begin selectable.

**Separate hue and opacity/alpha slider**
They somehow look like the same component, just different background styling? So maybe you could investigate wether it could be an option to have one component, but implemented twice with different background injected via CSS or a slot?

**Correct transform/convert of colors**
Feel free to pick what you find best. A Fork does though sound dangerous if its not begin maintained. So I would go for one that is maintained and light weight. The one Shoelace uses, sounds good just because they chose to use it, but I haven't investigated anything.

I hope that was the answers you were looking for, otherwise let me know and I can get some dedicated time to look into things :-)

**Comment by bjarnef** [comment]
@nielslyngsoe yes, I also think it would be great with a `<uui-color-swatch>` component to make it selectable, unselectable, disabled. Not sure how we control single/multi selection of these in `<uui-color-swatches>` though.

Regarding hue and opacity/alpha slider they are mostly identical. However in the Shoelace library the inner container had inline style calculated so rgba background color changed as the value in hue slider changed:
https://shoelace.style/components/color-picker?id=opacity

TinyColor may be familiar as we currently use include it Umbraco. However although the fork is maintained now, I am not sure it stay updated in future. The Color library used in Showlace seemed great is not as lightweight as Colord.
https://github.com/omgovich/colord

Based on the numbers Colord seems to be the best choice and we don't need to include all advanced functions/features if not used. 
image

**Pull request closed without merging**
