### PR TITLE
Specific control types in storybook controls

### PR DESCRIPTION
**Pull request by bjarnef**
## Description

This PR makes some enhancements reported in https://github.com/umbraco/Umbraco.UI/issues/535

From https://storybook.js.org/docs/7.0/react/essentials/controls#choosing-the-control-type
> By default, Storybook will choose a control for each arg based on the initial value of the arg. It works well with certain types of args, such as boolean values or free-text strings, but in other cases, you want a more restricted control.

In color picker we have some properties with specific values, where we can use the enum based controls instead.

I have also changes control type of `value` property to "color" control, which seems to work with both hex and rgba.
I updated the "With opacity" story with an initial value of `rgba(0, 0, 0, 0.5)` to demonstrate an initial value with opacity and the control type is set to this as well.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Screenshots (if appropriate)

image

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [ ] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.UI/blob/dev/docs/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by iOvergaard** [comment]
Looks good to me, @bjarnef! Would you run prettier on the files to make sure it passes the tests? Then I'll get it merged :)

**Comment by bjarnef** [comment]
@iOvergaard I executed `npm run format`.
Apparently it wants end comma although not required.

**Comment by bjarnef** [comment]
@iOvergaard any changes required for this or can it be merged? :)

**Comment by bjarnef** [comment]
Updated this with support of HSV color format in https://github.com/umbraco/Umbraco.UI/pull/610

**Pull request merged**
