### PR TITLE
Set correct values for aria-checked attribute

### PR DESCRIPTION
**Pull request by bjarnef**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

- [ ] If my change requires a change to the documentation, I have updated the documentation in this pull request.
- [x] I have read the **[CONTRIBUTING](<(https://github.com/umbraco/Umbraco.UI/blob/v1/contrib/docs/CONTRIBUTING.md)>)** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by bjarnef** [comment]
It seems we still get errors with this changes, which it solved added `role` attribute. However then it doesn't like the nested `<input type="radio" />`.

Do we really need the hidden `<input>` element, when we create a custom element? It seems most other web component libraries doesn't include this, but directly attributes on the elements.

**Comment by bjarnef** [comment]
It seems it still cause some error though, but could be looked at in a different PR.

**Comment by iOvergaard** [comment]
@bjarnef I see the tests are failing here because of this attribute. 

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked), they prefer to use input type="radio" or type="checkbox" instead:

> Where possible use an HTML [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element with type="checkbox" and type="radio" as these have built in semantics and do not require ARIA attributes.

The uui-radio has a `type="radio"` element underneath, so are we sure we even need the `aria-checked` attribute in the first place?

**Comment by bjarnef** [comment]
@iOvergaard yes elements having `checked`, `indetermidate` etc. are accessible by default and doesn't need this.
When wrapping these and hiding the original input I am not sure if the parent still need these though.

The radiobutton has some issues due the tabindex and child hidden radiobutton, when require double hits on tabs key to focus these unlike checkbox.

**Comment by iOvergaard** [comment]
> @iOvergaard yes elements having `checked`, `indetermidate` etc. are accessible by default and doesn't need this. When wrapping these and hiding the original input I am not sure if the parent still need these though.
> 
> The radiobutton has some issues due the tabindex and child hidden radiobutton, when require double hits on tabs key to focus these unlike checkbox.

According to our analysis, we don't need aria-checked on these elements. Meanwhile, we have also discovered a host of other issues with radio and radio group. We are going to look into it in another PR. Thanks for your feedback here :-)

**Pull request closed without merging**
